Repository siteorigin/so-widgets-bundle, pull requests merged in 2019-12, with the labels that each got.

#933 Removed media fallback field padding
  base/inc/fields/css/media-field.less
Labels: bug

#927 Removed static height declaration
  base/inc/fields/css/measurement-field.less
Labels: bug

#934 Added right margin to color picker input
  base/css/admin.less
Labels: bug

#936 Expanded dev emails list
  widgets/contact/contact.php
Labels: enhancement

#940 Set Font-display: swap on font imports
  base/base.php
Labels: enhancement

#943 Ensure correct alignment of Pixabay search button
  base/inc/fields/css/media-field.less
Labels: bug

#947 Better render media search field for mobile
  base/inc/fields/css/media-field.less
Labels: enhancement

#925 Contact: Check from field for dev emails and replace it
  widgets/contact/contact.php
Labels: enhancement

#939 "Pre-fill" hero if height is set
  widgets/hero/styles/default.less
Labels: bug, priority-2

#935 SiteOrigin Features: Allow Selection of Different Title Header Levels
  widgets/features/features.php
  widgets/features/styles/default.less
  widgets/features/tpl/default.php
Labels: enhancement
