Repository siteorigin/so-widgets-bundle, pull requests merged in 2020-01, with the labels that each got.

#950 Features: Add Fallback support for Icon Image
  widgets/features/features.php
  widgets/features/tpl/default.php
Labels: enhancement, priority-3

#961 Cursor not allowed for disabled button
  widgets/contact/styles/default.less
Labels: bug, priority-2

#960 Change measurement field to use only right margin
  base/inc/fields/css/measurement-field.less
Labels: bug, priority-2

#949 Account for false values when setting default values rather than just empty values
  base/inc/routes/siteorigin-widgets-resource.class.php
Labels: bug, priority-2

#964 Switch media field and external URL margin
  base/inc/fields/css/media-field.less
Labels: bug

#966 BE fix media button
  base/inc/fields/css/media-field.less
Labels: bug, priority-2

#975 Updated media button right margin
  base/inc/fields/css/media-field.less
Labels: bug
